import type { Metadata } from "next"
import { Roboto } from "next/font/google"

import "./globals.css"
import Navbar from "./components/navbar"
import Footer from "./components/footer"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
    recent_products: React.ReactNode
    categories: React.ReactNode
  }>
) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable} antialiased`}>
        <Navbar />
        {props.children}
        {props.categories}
        {props.recent_products}
        <Footer />
      </body>
    </html>
  )
}
